/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.EnergyModel;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Energy Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl#getConsumptionRate <em>Consumption Rate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl#getBatteryHealth <em>Battery Health</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl#getCapacity <em>Capacity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnergyModelImpl extends MinimalEObjectImpl.Container implements EnergyModel
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getConsumptionRate() <em>Consumption Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConsumptionRate()
   * @generated
   * @ordered
   */
  protected static final String CONSUMPTION_RATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConsumptionRate() <em>Consumption Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConsumptionRate()
   * @generated
   * @ordered
   */
  protected String consumptionRate = CONSUMPTION_RATE_EDEFAULT;

  /**
   * The default value of the '{@link #getBatteryHealth() <em>Battery Health</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBatteryHealth()
   * @generated
   * @ordered
   */
  protected static final String BATTERY_HEALTH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBatteryHealth() <em>Battery Health</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBatteryHealth()
   * @generated
   * @ordered
   */
  protected String batteryHealth = BATTERY_HEALTH_EDEFAULT;

  /**
   * The default value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected static final String CAPACITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected String capacity = CAPACITY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnergyModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ENERGY_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENERGY_MODEL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getConsumptionRate()
  {
    return consumptionRate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConsumptionRate(String newConsumptionRate)
  {
    String oldConsumptionRate = consumptionRate;
    consumptionRate = newConsumptionRate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENERGY_MODEL__CONSUMPTION_RATE, oldConsumptionRate, consumptionRate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBatteryHealth()
  {
    return batteryHealth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBatteryHealth(String newBatteryHealth)
  {
    String oldBatteryHealth = batteryHealth;
    batteryHealth = newBatteryHealth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENERGY_MODEL__BATTERY_HEALTH, oldBatteryHealth, batteryHealth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCapacity()
  {
    return capacity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCapacity(String newCapacity)
  {
    String oldCapacity = capacity;
    capacity = newCapacity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENERGY_MODEL__CAPACITY, oldCapacity, capacity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ENERGY_MODEL__NAME:
        return getName();
      case MyDslPackage.ENERGY_MODEL__CONSUMPTION_RATE:
        return getConsumptionRate();
      case MyDslPackage.ENERGY_MODEL__BATTERY_HEALTH:
        return getBatteryHealth();
      case MyDslPackage.ENERGY_MODEL__CAPACITY:
        return getCapacity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ENERGY_MODEL__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.ENERGY_MODEL__CONSUMPTION_RATE:
        setConsumptionRate((String)newValue);
        return;
      case MyDslPackage.ENERGY_MODEL__BATTERY_HEALTH:
        setBatteryHealth((String)newValue);
        return;
      case MyDslPackage.ENERGY_MODEL__CAPACITY:
        setCapacity((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ENERGY_MODEL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.ENERGY_MODEL__CONSUMPTION_RATE:
        setConsumptionRate(CONSUMPTION_RATE_EDEFAULT);
        return;
      case MyDslPackage.ENERGY_MODEL__BATTERY_HEALTH:
        setBatteryHealth(BATTERY_HEALTH_EDEFAULT);
        return;
      case MyDslPackage.ENERGY_MODEL__CAPACITY:
        setCapacity(CAPACITY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ENERGY_MODEL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.ENERGY_MODEL__CONSUMPTION_RATE:
        return CONSUMPTION_RATE_EDEFAULT == null ? consumptionRate != null : !CONSUMPTION_RATE_EDEFAULT.equals(consumptionRate);
      case MyDslPackage.ENERGY_MODEL__BATTERY_HEALTH:
        return BATTERY_HEALTH_EDEFAULT == null ? batteryHealth != null : !BATTERY_HEALTH_EDEFAULT.equals(batteryHealth);
      case MyDslPackage.ENERGY_MODEL__CAPACITY:
        return CAPACITY_EDEFAULT == null ? capacity != null : !CAPACITY_EDEFAULT.equals(capacity);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", consumptionRate: ");
    result.append(consumptionRate);
    result.append(", batteryHealth: ");
    result.append(batteryHealth);
    result.append(", capacity: ");
    result.append(capacity);
    result.append(')');
    return result.toString();
  }

} //EnergyModelImpl
