/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Drone</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Drone#getIp <em>Ip</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Drone#getSerialNumber <em>Serial Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDrone()
 * @model
 * @generated
 */
public interface Drone extends Entity
{
  /**
   * Returns the value of the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip</em>' attribute.
   * @see #setIp(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDrone_Ip()
   * @model
   * @generated
   */
  String getIp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Drone#getIp <em>Ip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip</em>' attribute.
   * @see #getIp()
   * @generated
   */
  void setIp(String value);

  /**
   * Returns the value of the '<em><b>Serial Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Serial Number</em>' attribute.
   * @see #setSerialNumber(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDrone_SerialNumber()
   * @model
   * @generated
   */
  String getSerialNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Drone#getSerialNumber <em>Serial Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Serial Number</em>' attribute.
   * @see #getSerialNumber()
   * @generated
   */
  void setSerialNumber(String value);

} // Drone
