/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Energy Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EnergyModel#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EnergyModel#getConsumptionRate <em>Consumption Rate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EnergyModel#getBatteryHealth <em>Battery Health</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EnergyModel#getCapacity <em>Capacity</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEnergyModel()
 * @model
 * @generated
 */
public interface EnergyModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEnergyModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Consumption Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consumption Rate</em>' attribute.
   * @see #setConsumptionRate(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEnergyModel_ConsumptionRate()
   * @model
   * @generated
   */
  String getConsumptionRate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getConsumptionRate <em>Consumption Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consumption Rate</em>' attribute.
   * @see #getConsumptionRate()
   * @generated
   */
  void setConsumptionRate(String value);

  /**
   * Returns the value of the '<em><b>Battery Health</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Battery Health</em>' attribute.
   * @see #setBatteryHealth(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEnergyModel_BatteryHealth()
   * @model
   * @generated
   */
  String getBatteryHealth();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getBatteryHealth <em>Battery Health</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Battery Health</em>' attribute.
   * @see #getBatteryHealth()
   * @generated
   */
  void setBatteryHealth(String value);

  /**
   * Returns the value of the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacity</em>' attribute.
   * @see #setCapacity(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEnergyModel_Capacity()
   * @model
   * @generated
   */
  String getCapacity();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getCapacity <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacity</em>' attribute.
   * @see #getCapacity()
   * @generated
   */
  void setCapacity(String value);

} // EnergyModel
