/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mission Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MissionEvent#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MissionEvent#getEventType <em>Event Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MissionEvent#getImpactLevel <em>Impact Level</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MissionEvent#getResponseAction <em>Response Action</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMissionEvent()
 * @model
 * @generated
 */
public interface MissionEvent extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMissionEvent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Event Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Type</em>' attribute.
   * @see #setEventType(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMissionEvent_EventType()
   * @model
   * @generated
   */
  String getEventType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getEventType <em>Event Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Type</em>' attribute.
   * @see #getEventType()
   * @generated
   */
  void setEventType(String value);

  /**
   * Returns the value of the '<em><b>Impact Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Impact Level</em>' attribute.
   * @see #setImpactLevel(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMissionEvent_ImpactLevel()
   * @model
   * @generated
   */
  int getImpactLevel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getImpactLevel <em>Impact Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Impact Level</em>' attribute.
   * @see #getImpactLevel()
   * @generated
   */
  void setImpactLevel(int value);

  /**
   * Returns the value of the '<em><b>Response Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response Action</em>' attribute.
   * @see #setResponseAction(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMissionEvent_ResponseAction()
   * @model
   * @generated
   */
  String getResponseAction();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getResponseAction <em>Response Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response Action</em>' attribute.
   * @see #getResponseAction()
   * @generated
   */
  void setResponseAction(String value);

} // MissionEvent
