/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Missions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MISSIONS = 0;

  /**
   * The feature id for the '<em><b>Drones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DRONES = 1;

  /**
   * The feature id for the '<em><b>Energy Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENERGY_MODELS = 2;

  /**
   * The feature id for the '<em><b>Phases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PHASES = 3;

  /**
   * The feature id for the '<em><b>Sub Phases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SUB_PHASES = 4;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ACTIONS = 5;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONSTRAINTS = 6;

  /**
   * The feature id for the '<em><b>Mission EVents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MISSION_EVENTS = 7;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MissionImpl <em>Mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MissionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMission()
   * @generated
   */
  int MISSION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__ID = 1;

  /**
   * The feature id for the '<em><b>Mission Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__MISSION_TYPE = 2;

  /**
   * The feature id for the '<em><b>Start Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__START_LOCATION = 3;

  /**
   * The feature id for the '<em><b>End Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__END_LOCATION = 4;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__PRIORITY = 5;

  /**
   * The feature id for the '<em><b>Estimated Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__ESTIMATED_TIME = 6;

  /**
   * The feature id for the '<em><b>Add Drones</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__ADD_DRONES = 7;

  /**
   * The feature id for the '<em><b>Add Phases</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__ADD_PHASES = 8;

  /**
   * The feature id for the '<em><b>Add Constraints</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__ADD_CONSTRAINTS = 9;

  /**
   * The feature id for the '<em><b>Add Events</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__ADD_EVENTS = 10;

  /**
   * The number of structural features of the '<em>Mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DroneImpl <em>Drone</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DroneImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDrone()
   * @generated
   */
  int DRONE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Batter Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__BATTER_CAPACITY = 2;

  /**
   * The feature id for the '<em><b>Max Flight Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__MAX_FLIGHT_TIME = 3;

  /**
   * The feature id for the '<em><b>Payload Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__PAYLOAD_CAPACITY = 4;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__ROLE = 5;

  /**
   * The feature id for the '<em><b>Add Energy Model</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE__ADD_ENERGY_MODEL = 6;

  /**
   * The number of structural features of the '<em>Drone</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRONE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl <em>Energy Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEnergyModel()
   * @generated
   */
  int ENERGY_MODEL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGY_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Consumption Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGY_MODEL__CONSUMPTION_RATE = 1;

  /**
   * The feature id for the '<em><b>Battery Health</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGY_MODEL__BATTERY_HEALTH = 2;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGY_MODEL__CAPACITY = 3;

  /**
   * The number of structural features of the '<em>Energy Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGY_MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PhaseImpl <em>Phase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PhaseImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPhase()
   * @generated
   */
  int PHASE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Phase Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE__PHASE_TYPE = 1;

  /**
   * The feature id for the '<em><b>Energy Usage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE__ENERGY_USAGE = 2;

  /**
   * The feature id for the '<em><b>Add Sub Phase</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE__ADD_SUB_PHASE = 3;

  /**
   * The number of structural features of the '<em>Phase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SubPhaseImpl <em>Sub Phase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SubPhaseImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubPhase()
   * @generated
   */
  int SUB_PHASE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PHASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Sub Phase Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PHASE__SUB_PHASE_TYPE = 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PHASE__DURATION = 2;

  /**
   * The feature id for the '<em><b>Add Action</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PHASE__ADD_ACTION = 3;

  /**
   * The number of structural features of the '<em>Sub Phase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PHASE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Action Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ACTION_TYPE = 1;

  /**
   * The feature id for the '<em><b>Input Output</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__INPUT_OUTPUT = 2;

  /**
   * The feature id for the '<em><b>Energy Usage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ENERGY_USAGE = 3;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ConstraintImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__NAME = 0;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SafetyConstraintImpl <em>Safety Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SafetyConstraintImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSafetyConstraint()
   * @generated
   */
  int SAFETY_CONSTRAINT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAFETY_CONSTRAINT__NAME = CONSTRAINT__NAME;

  /**
   * The feature id for the '<em><b>Min Battery</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAFETY_CONSTRAINT__MIN_BATTERY = CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max Wind Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAFETY_CONSTRAINT__MAX_WIND_SPEED = CONSTRAINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Safety Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAFETY_CONSTRAINT_FEATURE_COUNT = CONSTRAINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RegulatoryConstraintImpl <em>Regulatory Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RegulatoryConstraintImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRegulatoryConstraint()
   * @generated
   */
  int REGULATORY_CONSTRAINT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULATORY_CONSTRAINT__NAME = CONSTRAINT__NAME;

  /**
   * The feature id for the '<em><b>Flight Permission</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULATORY_CONSTRAINT__FLIGHT_PERMISSION = CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Altitude Limit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULATORY_CONSTRAINT__ALTITUDE_LIMIT = CONSTRAINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Regulatory Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGULATORY_CONSTRAINT_FEATURE_COUNT = CONSTRAINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MissionEventImpl <em>Mission Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MissionEventImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMissionEvent()
   * @generated
   */
  int MISSION_EVENT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Event Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_EVENT__EVENT_TYPE = 1;

  /**
   * The feature id for the '<em><b>Impact Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_EVENT__IMPACT_LEVEL = 2;

  /**
   * The feature id for the '<em><b>Response Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_EVENT__RESPONSE_ACTION = 3;

  /**
   * The number of structural features of the '<em>Mission Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_EVENT_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getMissions <em>Missions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Missions</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getMissions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Missions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getDrones <em>Drones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Drones</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getDrones()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Drones();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getEnergyModels <em>Energy Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Energy Models</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getEnergyModels()
   * @see #getModel()
   * @generated
   */
  EReference getModel_EnergyModels();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getPhases <em>Phases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Phases</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getPhases()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Phases();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getSubPhases <em>Sub Phases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Phases</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getSubPhases()
   * @see #getModel()
   * @generated
   */
  EReference getModel_SubPhases();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getActions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Actions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getConstraints()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Constraints();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getMissionEVents <em>Mission EVents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mission EVents</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getMissionEVents()
   * @see #getModel()
   * @generated
   */
  EReference getModel_MissionEVents();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission
   * @generated
   */
  EClass getMission();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mission#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getName()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mission#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getId()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mission#getMissionType <em>Mission Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mission Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getMissionType()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_MissionType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mission#getStartLocation <em>Start Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Location</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getStartLocation()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_StartLocation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mission#getEndLocation <em>End Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Location</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getEndLocation()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_EndLocation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mission#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getPriority()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Priority();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mission#getEstimatedTime <em>Estimated Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Estimated Time</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getEstimatedTime()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_EstimatedTime();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Mission#getAddDrones <em>Add Drones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Add Drones</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getAddDrones()
   * @see #getMission()
   * @generated
   */
  EReference getMission_AddDrones();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Mission#getAddPhases <em>Add Phases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Add Phases</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getAddPhases()
   * @see #getMission()
   * @generated
   */
  EReference getMission_AddPhases();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Mission#getAddConstraints <em>Add Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Add Constraints</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getAddConstraints()
   * @see #getMission()
   * @generated
   */
  EReference getMission_AddConstraints();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Mission#getAddEvents <em>Add Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Add Events</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mission#getAddEvents()
   * @see #getMission()
   * @generated
   */
  EReference getMission_AddEvents();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Drone <em>Drone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drone</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone
   * @generated
   */
  EClass getDrone();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Drone#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone#getName()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Drone#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone#getType()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Drone#getBatterCapacity <em>Batter Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Batter Capacity</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone#getBatterCapacity()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_BatterCapacity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Drone#getMaxFlightTime <em>Max Flight Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Flight Time</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone#getMaxFlightTime()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_MaxFlightTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Drone#getPayloadCapacity <em>Payload Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Payload Capacity</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone#getPayloadCapacity()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_PayloadCapacity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Drone#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone#getRole()
   * @see #getDrone()
   * @generated
   */
  EAttribute getDrone_Role();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Drone#getAddEnergyModel <em>Add Energy Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Add Energy Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Drone#getAddEnergyModel()
   * @see #getDrone()
   * @generated
   */
  EReference getDrone_AddEnergyModel();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.EnergyModel <em>Energy Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Energy Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.EnergyModel
   * @generated
   */
  EClass getEnergyModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.EnergyModel#getName()
   * @see #getEnergyModel()
   * @generated
   */
  EAttribute getEnergyModel_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getConsumptionRate <em>Consumption Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Consumption Rate</em>'.
   * @see org.xtext.example.mydsl.myDsl.EnergyModel#getConsumptionRate()
   * @see #getEnergyModel()
   * @generated
   */
  EAttribute getEnergyModel_ConsumptionRate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getBatteryHealth <em>Battery Health</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Battery Health</em>'.
   * @see org.xtext.example.mydsl.myDsl.EnergyModel#getBatteryHealth()
   * @see #getEnergyModel()
   * @generated
   */
  EAttribute getEnergyModel_BatteryHealth();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.EnergyModel#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.xtext.example.mydsl.myDsl.EnergyModel#getCapacity()
   * @see #getEnergyModel()
   * @generated
   */
  EAttribute getEnergyModel_Capacity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Phase <em>Phase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Phase</em>'.
   * @see org.xtext.example.mydsl.myDsl.Phase
   * @generated
   */
  EClass getPhase();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Phase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Phase#getName()
   * @see #getPhase()
   * @generated
   */
  EAttribute getPhase_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Phase#getPhaseType <em>Phase Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phase Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Phase#getPhaseType()
   * @see #getPhase()
   * @generated
   */
  EAttribute getPhase_PhaseType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Phase#getEnergyUsage <em>Energy Usage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Energy Usage</em>'.
   * @see org.xtext.example.mydsl.myDsl.Phase#getEnergyUsage()
   * @see #getPhase()
   * @generated
   */
  EAttribute getPhase_EnergyUsage();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Phase#getAddSubPhase <em>Add Sub Phase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Add Sub Phase</em>'.
   * @see org.xtext.example.mydsl.myDsl.Phase#getAddSubPhase()
   * @see #getPhase()
   * @generated
   */
  EReference getPhase_AddSubPhase();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SubPhase <em>Sub Phase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Phase</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubPhase
   * @generated
   */
  EClass getSubPhase();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SubPhase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubPhase#getName()
   * @see #getSubPhase()
   * @generated
   */
  EAttribute getSubPhase_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SubPhase#getSubPhaseType <em>Sub Phase Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sub Phase Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubPhase#getSubPhaseType()
   * @see #getSubPhase()
   * @generated
   */
  EAttribute getSubPhase_SubPhaseType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SubPhase#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubPhase#getDuration()
   * @see #getSubPhase()
   * @generated
   */
  EAttribute getSubPhase_Duration();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.SubPhase#getAddAction <em>Add Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Add Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubPhase#getAddAction()
   * @see #getSubPhase()
   * @generated
   */
  EReference getSubPhase_AddAction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Action#getActionType <em>Action Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action#getActionType()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_ActionType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Action#getInputOutput <em>Input Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Input Output</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action#getInputOutput()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_InputOutput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Action#getEnergyUsage <em>Energy Usage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Energy Usage</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action#getEnergyUsage()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_EnergyUsage();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see org.xtext.example.mydsl.myDsl.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Constraint#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Constraint#getName()
   * @see #getConstraint()
   * @generated
   */
  EAttribute getConstraint_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SafetyConstraint <em>Safety Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Safety Constraint</em>'.
   * @see org.xtext.example.mydsl.myDsl.SafetyConstraint
   * @generated
   */
  EClass getSafetyConstraint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SafetyConstraint#getMinBattery <em>Min Battery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Battery</em>'.
   * @see org.xtext.example.mydsl.myDsl.SafetyConstraint#getMinBattery()
   * @see #getSafetyConstraint()
   * @generated
   */
  EAttribute getSafetyConstraint_MinBattery();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SafetyConstraint#getMaxWindSpeed <em>Max Wind Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Wind Speed</em>'.
   * @see org.xtext.example.mydsl.myDsl.SafetyConstraint#getMaxWindSpeed()
   * @see #getSafetyConstraint()
   * @generated
   */
  EAttribute getSafetyConstraint_MaxWindSpeed();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.RegulatoryConstraint <em>Regulatory Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regulatory Constraint</em>'.
   * @see org.xtext.example.mydsl.myDsl.RegulatoryConstraint
   * @generated
   */
  EClass getRegulatoryConstraint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RegulatoryConstraint#getFlightPermission <em>Flight Permission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Flight Permission</em>'.
   * @see org.xtext.example.mydsl.myDsl.RegulatoryConstraint#getFlightPermission()
   * @see #getRegulatoryConstraint()
   * @generated
   */
  EAttribute getRegulatoryConstraint_FlightPermission();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RegulatoryConstraint#getAltitudeLimit <em>Altitude Limit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Altitude Limit</em>'.
   * @see org.xtext.example.mydsl.myDsl.RegulatoryConstraint#getAltitudeLimit()
   * @see #getRegulatoryConstraint()
   * @generated
   */
  EAttribute getRegulatoryConstraint_AltitudeLimit();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.MissionEvent <em>Mission Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission Event</em>'.
   * @see org.xtext.example.mydsl.myDsl.MissionEvent
   * @generated
   */
  EClass getMissionEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.MissionEvent#getName()
   * @see #getMissionEvent()
   * @generated
   */
  EAttribute getMissionEvent_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getEventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.MissionEvent#getEventType()
   * @see #getMissionEvent()
   * @generated
   */
  EAttribute getMissionEvent_EventType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getImpactLevel <em>Impact Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Impact Level</em>'.
   * @see org.xtext.example.mydsl.myDsl.MissionEvent#getImpactLevel()
   * @see #getMissionEvent()
   * @generated
   */
  EAttribute getMissionEvent_ImpactLevel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MissionEvent#getResponseAction <em>Response Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Response Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.MissionEvent#getResponseAction()
   * @see #getMissionEvent()
   * @generated
   */
  EAttribute getMissionEvent_ResponseAction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Missions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MISSIONS = eINSTANCE.getModel_Missions();

    /**
     * The meta object literal for the '<em><b>Drones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DRONES = eINSTANCE.getModel_Drones();

    /**
     * The meta object literal for the '<em><b>Energy Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENERGY_MODELS = eINSTANCE.getModel_EnergyModels();

    /**
     * The meta object literal for the '<em><b>Phases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PHASES = eINSTANCE.getModel_Phases();

    /**
     * The meta object literal for the '<em><b>Sub Phases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SUB_PHASES = eINSTANCE.getModel_SubPhases();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ACTIONS = eINSTANCE.getModel_Actions();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONSTRAINTS = eINSTANCE.getModel_Constraints();

    /**
     * The meta object literal for the '<em><b>Mission EVents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MISSION_EVENTS = eINSTANCE.getModel_MissionEVents();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MissionImpl <em>Mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MissionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getMission();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__NAME = eINSTANCE.getMission_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__ID = eINSTANCE.getMission_Id();

    /**
     * The meta object literal for the '<em><b>Mission Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__MISSION_TYPE = eINSTANCE.getMission_MissionType();

    /**
     * The meta object literal for the '<em><b>Start Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__START_LOCATION = eINSTANCE.getMission_StartLocation();

    /**
     * The meta object literal for the '<em><b>End Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__END_LOCATION = eINSTANCE.getMission_EndLocation();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__PRIORITY = eINSTANCE.getMission_Priority();

    /**
     * The meta object literal for the '<em><b>Estimated Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__ESTIMATED_TIME = eINSTANCE.getMission_EstimatedTime();

    /**
     * The meta object literal for the '<em><b>Add Drones</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__ADD_DRONES = eINSTANCE.getMission_AddDrones();

    /**
     * The meta object literal for the '<em><b>Add Phases</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__ADD_PHASES = eINSTANCE.getMission_AddPhases();

    /**
     * The meta object literal for the '<em><b>Add Constraints</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__ADD_CONSTRAINTS = eINSTANCE.getMission_AddConstraints();

    /**
     * The meta object literal for the '<em><b>Add Events</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__ADD_EVENTS = eINSTANCE.getMission_AddEvents();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DroneImpl <em>Drone</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DroneImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDrone()
     * @generated
     */
    EClass DRONE = eINSTANCE.getDrone();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__NAME = eINSTANCE.getDrone_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__TYPE = eINSTANCE.getDrone_Type();

    /**
     * The meta object literal for the '<em><b>Batter Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__BATTER_CAPACITY = eINSTANCE.getDrone_BatterCapacity();

    /**
     * The meta object literal for the '<em><b>Max Flight Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__MAX_FLIGHT_TIME = eINSTANCE.getDrone_MaxFlightTime();

    /**
     * The meta object literal for the '<em><b>Payload Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__PAYLOAD_CAPACITY = eINSTANCE.getDrone_PayloadCapacity();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRONE__ROLE = eINSTANCE.getDrone_Role();

    /**
     * The meta object literal for the '<em><b>Add Energy Model</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DRONE__ADD_ENERGY_MODEL = eINSTANCE.getDrone_AddEnergyModel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl <em>Energy Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.EnergyModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEnergyModel()
     * @generated
     */
    EClass ENERGY_MODEL = eINSTANCE.getEnergyModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENERGY_MODEL__NAME = eINSTANCE.getEnergyModel_Name();

    /**
     * The meta object literal for the '<em><b>Consumption Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENERGY_MODEL__CONSUMPTION_RATE = eINSTANCE.getEnergyModel_ConsumptionRate();

    /**
     * The meta object literal for the '<em><b>Battery Health</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENERGY_MODEL__BATTERY_HEALTH = eINSTANCE.getEnergyModel_BatteryHealth();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENERGY_MODEL__CAPACITY = eINSTANCE.getEnergyModel_Capacity();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PhaseImpl <em>Phase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PhaseImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPhase()
     * @generated
     */
    EClass PHASE = eINSTANCE.getPhase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PHASE__NAME = eINSTANCE.getPhase_Name();

    /**
     * The meta object literal for the '<em><b>Phase Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PHASE__PHASE_TYPE = eINSTANCE.getPhase_PhaseType();

    /**
     * The meta object literal for the '<em><b>Energy Usage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PHASE__ENERGY_USAGE = eINSTANCE.getPhase_EnergyUsage();

    /**
     * The meta object literal for the '<em><b>Add Sub Phase</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASE__ADD_SUB_PHASE = eINSTANCE.getPhase_AddSubPhase();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SubPhaseImpl <em>Sub Phase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SubPhaseImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubPhase()
     * @generated
     */
    EClass SUB_PHASE = eINSTANCE.getSubPhase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_PHASE__NAME = eINSTANCE.getSubPhase_Name();

    /**
     * The meta object literal for the '<em><b>Sub Phase Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_PHASE__SUB_PHASE_TYPE = eINSTANCE.getSubPhase_SubPhaseType();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_PHASE__DURATION = eINSTANCE.getSubPhase_Duration();

    /**
     * The meta object literal for the '<em><b>Add Action</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_PHASE__ADD_ACTION = eINSTANCE.getSubPhase_AddAction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '<em><b>Action Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ACTION_TYPE = eINSTANCE.getAction_ActionType();

    /**
     * The meta object literal for the '<em><b>Input Output</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__INPUT_OUTPUT = eINSTANCE.getAction_InputOutput();

    /**
     * The meta object literal for the '<em><b>Energy Usage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ENERGY_USAGE = eINSTANCE.getAction_EnergyUsage();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ConstraintImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRAINT__NAME = eINSTANCE.getConstraint_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SafetyConstraintImpl <em>Safety Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SafetyConstraintImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSafetyConstraint()
     * @generated
     */
    EClass SAFETY_CONSTRAINT = eINSTANCE.getSafetyConstraint();

    /**
     * The meta object literal for the '<em><b>Min Battery</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAFETY_CONSTRAINT__MIN_BATTERY = eINSTANCE.getSafetyConstraint_MinBattery();

    /**
     * The meta object literal for the '<em><b>Max Wind Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAFETY_CONSTRAINT__MAX_WIND_SPEED = eINSTANCE.getSafetyConstraint_MaxWindSpeed();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RegulatoryConstraintImpl <em>Regulatory Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RegulatoryConstraintImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRegulatoryConstraint()
     * @generated
     */
    EClass REGULATORY_CONSTRAINT = eINSTANCE.getRegulatoryConstraint();

    /**
     * The meta object literal for the '<em><b>Flight Permission</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGULATORY_CONSTRAINT__FLIGHT_PERMISSION = eINSTANCE.getRegulatoryConstraint_FlightPermission();

    /**
     * The meta object literal for the '<em><b>Altitude Limit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGULATORY_CONSTRAINT__ALTITUDE_LIMIT = eINSTANCE.getRegulatoryConstraint_AltitudeLimit();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MissionEventImpl <em>Mission Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MissionEventImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMissionEvent()
     * @generated
     */
    EClass MISSION_EVENT = eINSTANCE.getMissionEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION_EVENT__NAME = eINSTANCE.getMissionEvent_Name();

    /**
     * The meta object literal for the '<em><b>Event Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION_EVENT__EVENT_TYPE = eINSTANCE.getMissionEvent_EventType();

    /**
     * The meta object literal for the '<em><b>Impact Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION_EVENT__IMPACT_LEVEL = eINSTANCE.getMissionEvent_ImpactLevel();

    /**
     * The meta object literal for the '<em><b>Response Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION_EVENT__RESPONSE_ACTION = eINSTANCE.getMissionEvent_ResponseAction();

  }

} //MyDslPackage
