/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Phase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Phase#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Phase#getPhaseType <em>Phase Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Phase#getEnergyUsage <em>Energy Usage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Phase#getAddSubPhase <em>Add Sub Phase</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPhase()
 * @model
 * @generated
 */
public interface Phase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPhase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Phase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Phase Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phase Type</em>' attribute.
   * @see #setPhaseType(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPhase_PhaseType()
   * @model
   * @generated
   */
  String getPhaseType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Phase#getPhaseType <em>Phase Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phase Type</em>' attribute.
   * @see #getPhaseType()
   * @generated
   */
  void setPhaseType(String value);

  /**
   * Returns the value of the '<em><b>Energy Usage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Energy Usage</em>' attribute.
   * @see #setEnergyUsage(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPhase_EnergyUsage()
   * @model
   * @generated
   */
  String getEnergyUsage();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Phase#getEnergyUsage <em>Energy Usage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Energy Usage</em>' attribute.
   * @see #getEnergyUsage()
   * @generated
   */
  void setEnergyUsage(String value);

  /**
   * Returns the value of the '<em><b>Add Sub Phase</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.SubPhase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Sub Phase</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPhase_AddSubPhase()
   * @model
   * @generated
   */
  EList<SubPhase> getAddSubPhase();

} // Phase
